version: "3.3"

services:
  postgres_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  web:
    build: .
    restart: always
    command: python /Manga/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Manga
    ports:
      - 8000:8000
    depends_on:
      - postgres_db

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - postgres_db
      - web
    ports:
      - "80:80"
      - "440:440"

volumes:
  postgres_data:
