version: "3.3"

services:
  database:
    image: postgres:latest
    hostname: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      -  5434:5432
    env_file:
      - ./.env

  web:
    build: .
    command: python /Manga/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Manga
    ports:
      - 8000:8000
    depends_on:
      - database

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - database
      - web
    ports:
      - "80:80"
      - "440:440"

volumes:
  postgres_data:
